### ISSUE TITLE
Ability to set both primary and fallback TTS to ovos-tts-server

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-tts-server#12]
Currently, this option works great for either a primary TTS server or a fallback TTS server. However, if I want to use it for primary **and** fallback, I cannot. There is no way to differentiate them in the config.

Ideally we could use ovos-tts-server for both TTS configurations and keep everything local and private.

**Comment by mikejgray** [comment]
@JarbasAl This is supported now, right?

**Comment by JarbasAl** [comment]
same as STT, accepts a list of urls now

closing
